//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteShare.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ProfessorName { get; set; }
        public int UniversityId { get; set; }
        public string Department { get; set; }
        public int Year { get; set; }
        public string Semester { get; set; }
    }
}
