//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteShare.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string AdmissionURL { get; set; }
        public string FinancialAidUrl { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Telephone { get; set; }
        public string Chancellor { get; set; }
    }
}
